name: Dependabot Actions
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - "dependabot/**"

jobs:
  print-versions:
    name: Print workspace
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_WORKSPACE
