name: Dependabot Actions
on:
  pull_request:
    types: [opened]
    branches:
      - "dependabot/**"

jobs:
  print-versions:
    name: Print current package versions
    runs-on: ubuntu-latest
    steps:
      - run: dpkg -l | grep ii
